# Generated by Django 5.1.5 on 2026-05-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0010_delete_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='pay_rate',
        ),
        migrations.AddField(
            model_name='members',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='members',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
